language: python
python:
        - '3.5'

before_script:
        - pip install -r requirements.txt
        - chmod +x manage.py

branches:
        only:
                -staging

env: DJANGO_SETTINGS_MODULE="nutella_project.settings.travis"

services:
        - mysql

script:
        - ./manage.py test
