# Generated by Django 2.0.3 on 2018-06-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Réservation'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Magasin'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(default='2018-06-10', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Adresse Mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='password',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mot de Passe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutri_score',
            field=models.IntegerField(verbose_name='Score Nutritionnel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.URLField(verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='research',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
    ]
