# Generated by Django 2.0.3 on 2018-06-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180610_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
